# -*- coding: utf-8 -*-
from . import multi_channel_sale
from . import channel_skeleton
from . import category_skeleton
from . import product_skeleton
from . import account_skeleton
from . import order_skeleton
from . import partner_skeleton
from . import shipping_skeleton
from . import channel_syncronization
from . import inherits
from . import multi_channel_skeleton
from . import pricelist_skeleton
from . import feeds
from . import order_feed
from . import shipping_feed
from . import attribute_value_skeleton
from . import res_config
from . import stock
